# Generated by Django 4.1 on 2022-09-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_url', models.URLField()),
                ('the_desc', models.CharField(max_length=200)),
                ('the_icon', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_quote', models.CharField(max_length=800)),
                ('the_author', models.CharField(max_length=50)),
                ('the_source', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
